// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aeizfksgslrxczhwdwik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlaXpma3Nnc2xyeGN6aHdkd2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzQ1NzEsImV4cCI6MjA2NjM1MDU3MX0.Jo4jvZGBtdBViOU-aKlpZdFOZVMEMkd7lbJ6GW0TwV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);